# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zedboard_dpu/zedboard_dpu.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zedboard_dpu || ORIG_REF_NAME==zedboard_dpu} -quiet] -quiet

# IP: bd/zedboard_dpu/ip/zedboard_dpu_processing_system7_0_0/zedboard_dpu_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zedboard_dpu_processing_system7_0_0 || ORIG_REF_NAME==zedboard_dpu_processing_system7_0_0} -quiet] -quiet

# IP: bd/zedboard_dpu/ip/zedboard_dpu_dpu_eu_0_0/zedboard_dpu_dpu_eu_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zedboard_dpu_dpu_eu_0_0 || ORIG_REF_NAME==zedboard_dpu_dpu_eu_0_0} -quiet] -quiet

# IP: bd/zedboard_dpu/ip/zedboard_dpu_xlconcat_0_0/zedboard_dpu_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zedboard_dpu_xlconcat_0_0 || ORIG_REF_NAME==zedboard_dpu_xlconcat_0_0} -quiet] -quiet

# IP: bd/zedboard_dpu/ip/zedboard_dpu_proc_sys_reset_0_0/zedboard_dpu_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zedboard_dpu_proc_sys_reset_0_0 || ORIG_REF_NAME==zedboard_dpu_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/zedboard_dpu/ip/zedboard_dpu_proc_sys_reset_0_1/zedboard_dpu_proc_sys_reset_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zedboard_dpu_proc_sys_reset_0_1 || ORIG_REF_NAME==zedboard_dpu_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/zedboard_dpu/ip/zedboard_dpu_proc_sys_reset_0_2/zedboard_dpu_proc_sys_reset_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zedboard_dpu_proc_sys_reset_0_2 || ORIG_REF_NAME==zedboard_dpu_proc_sys_reset_0_2} -quiet] -quiet

# IP: bd/zedboard_dpu/ip/zedboard_dpu_clk_wiz_0_0/zedboard_dpu_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zedboard_dpu_clk_wiz_0_0 || ORIG_REF_NAME==zedboard_dpu_clk_wiz_0_0} -quiet] -quiet

# XDC: bd/zedboard_dpu/zedboard_dpu_ooc.xdc
